import { Formik, Form, Field, ErrorMessage } from "formik";
import * as Yup from "yup";

export default function FormikForm() {
	  const validationSchema = Yup.object({
		      username: Yup.string().required("Username is required"),
		      email: Yup.string().email("Invalid email").required("Email is required"),
		      password: Yup.string().min(6, "Password must be at least 6 chars").required("Password is required"),
		    });

	  const handleSubmit = (values, { resetForm }) => {
		      console.log("Formik submitted:", values);

		      // mock API call
		  //     fetch("https://jsonplaceholder.typicode.com/users", {
		  //           method: "POST",
		  //                 body: JSON.stringify(values),
		  //                       headers: { "Content-Type": "application/json" },
		  //                           })
		  //                                 .then((res) => res.json())
		  //                                       .then((data) => console.log("Mock API Response:", data));
		  //
		  //                                           resetForm();
		  //                                             };
		  //
		  //                                               return (
		  //                                                   <div className="max-w-md mx-auto mt-10 p-6 bg-gray-100 rounded-lg shadow-md">
		  //                                                         <h2 className="text-2xl font-bold mb-4">Register (Formik)</h2>
		  //
		  //                                                               <Formik
		  //                                                                       initialValues={{ username: "", email: "", password: "" }}
		  //                                                                               validationSchema={validationSchema}
		  //                                                                                       onSubmit={handleSubmit}
		  //                                                                                             >
		  //                                                                                                     <Form className="space-y-4">
		  //                                                                                                               <div>
		  //                                                                                                                           <Field
		  //                                                                                                                                         type="text"
		  //                                                                                                                                                       name="username"
		  //                                                                                                                                                                     placeholder="Username"
		  //                                                                                                                                                                                   className="w-full p-2 border rounded"
		  //                                                                                                                                                                                               />
		  //                                                                                                                                                                                                           <ErrorMessage
		  //                                                                                                                                                                                                                         name="username"
		  //                                                                                                                                                                                                                                       component="div"
		  //                                                                                                                                                                                                                                                     className="text-red-500 text-sm"
		  //                                                                                                                                                                                                                                                                 />
		  //                                                                                                                                                                                                                                                                           </div>
		  //
		  //                                                                                                                                                                                                                                                                                     <div>
		  //                                                                                                                                                                                                                                                                                                 <Field
		  //                                                                                                                                                                                                                                                                                                               type="email"
		  //                                                                                                                                                                                                                                                                                                                             name="email"
		  //                                                                                                                                                                                                                                                                                                                                           placeholder="Email"
		  //                                                                                                                                                                                                                                                                                                                                                         className="w-full p-2 border rounded"
		  //                                                                                                                                                                                                                                                                                                                                                                     />
		  //                                                                                                                                                                                                                                                                                                                                                                                 <ErrorMessage
		  //                                                                                                                                                                                                                                                                                                                                                                                               name="email"
		  //                                                                                                                                                                                                                                                                                                                                                                                                             component="div"
		  //                                                                                                                                                                                                                                                                                                                                                                                                                           className="text-red-500 text-sm"
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                       />
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
		  //
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                           <div>
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <Field
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     type="password"
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   name="password"
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 placeholder="Password"
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               className="w-full p-2 border rounded"
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           />
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <ErrorMessage
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     name="password"
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   component="div"
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 className="text-red-500 text-sm"
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             />
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
		  //
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <button
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             type="submit"
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         className="w-full bg-green-600 text-white py-2 rounded hover:bg-green-700"
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   >
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Register
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </button>
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </Form>
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </Formik>
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             );
		  //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
		  //
